name: Native Rez packages

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - 'python-*'
      - '!python-*-pbs-*'

permissions:
  contents: write

jobs:
  native:
    uses: vx-org/vx-rez-packages/.github/workflows/runtime-release.yml@8ca39f087bee99307e9bd5f2b61b1915791df581
    with:
      tooling-ref: 8ca39f087bee99307e9bd5f2b61b1915791df581
      publish: ${{ github.event_name == 'push' }}
